package hibernate;
// Generated Jul 6, 2017 9:30:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Agenda generated by hbm2java
 */
public class Agenda  implements java.io.Serializable {


     private Integer id;
     private Conference conference;
     private Date beginDate;
     private Date endDate;
     private Set<Openceremony> openceremonies = new HashSet<Openceremony>(0);
     private Set<Myagenda> myagendas = new HashSet<Myagenda>(0);
     private Set<Sessionpause> sessionpauses = new HashSet<Sessionpause>(0);
     private Set<Sessions> sessionses = new HashSet<Sessions>(0);
     private Set<Closeceremony> closeceremonies = new HashSet<Closeceremony>(0);
     private Set<Workshop> workshops = new HashSet<Workshop>(0);

    public Agenda() {
    }

	
    public Agenda(Conference conference, Date beginDate, Date endDate) {
        this.conference = conference;
        this.beginDate = beginDate;
        this.endDate = endDate;
    }
    public Agenda(Conference conference, Date beginDate, Date endDate, Set<Openceremony> openceremonies, Set<Myagenda> myagendas, Set<Sessionpause> sessionpauses, Set<Sessions> sessionses, Set<Closeceremony> closeceremonies, Set<Workshop> workshops) {
       this.conference = conference;
       this.beginDate = beginDate;
       this.endDate = endDate;
       this.openceremonies = openceremonies;
       this.myagendas = myagendas;
       this.sessionpauses = sessionpauses;
       this.sessionses = sessionses;
       this.closeceremonies = closeceremonies;
       this.workshops = workshops;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Conference getConference() {
        return this.conference;
    }
    
    public void setConference(Conference conference) {
        this.conference = conference;
    }
    public Date getBeginDate() {
        return this.beginDate;
    }
    
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public Set<Openceremony> getOpenceremonies() {
        return this.openceremonies;
    }
    
    public void setOpenceremonies(Set<Openceremony> openceremonies) {
        this.openceremonies = openceremonies;
    }
    public Set<Myagenda> getMyagendas() {
        return this.myagendas;
    }
    
    public void setMyagendas(Set<Myagenda> myagendas) {
        this.myagendas = myagendas;
    }
    public Set<Sessionpause> getSessionpauses() {
        return this.sessionpauses;
    }
    
    public void setSessionpauses(Set<Sessionpause> sessionpauses) {
        this.sessionpauses = sessionpauses;
    }
    public Set<Sessions> getSessionses() {
        return this.sessionses;
    }
    
    public void setSessionses(Set<Sessions> sessionses) {
        this.sessionses = sessionses;
    }
    public Set<Closeceremony> getCloseceremonies() {
        return this.closeceremonies;
    }
    
    public void setCloseceremonies(Set<Closeceremony> closeceremonies) {
        this.closeceremonies = closeceremonies;
    }
    public Set<Workshop> getWorkshops() {
        return this.workshops;
    }
    
    public void setWorkshops(Set<Workshop> workshops) {
        this.workshops = workshops;
    }




}


