package hibernate;
// Generated Jul 6, 2017 9:30:01 PM by Hibernate Tools 4.3.1



/**
 * Author generated by hbm2java
 */
public class Author  implements java.io.Serializable {


     private Integer id;
     private Lecture lecture;
     private Workshop workshop;
     private String username;
     private int inDb;
     private int presenting;

    public Author() {
    }

	
    public Author(String username, int inDb, int presenting) {
        this.username = username;
        this.inDb = inDb;
        this.presenting = presenting;
    }
    public Author(Lecture lecture, Workshop workshop, String username, int inDb, int presenting) {
       this.lecture = lecture;
       this.workshop = workshop;
       this.username = username;
       this.inDb = inDb;
       this.presenting = presenting;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Lecture getLecture() {
        return this.lecture;
    }
    
    public void setLecture(Lecture lecture) {
        this.lecture = lecture;
    }
    public Workshop getWorkshop() {
        return this.workshop;
    }
    
    public void setWorkshop(Workshop workshop) {
        this.workshop = workshop;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public int getInDb() {
        return this.inDb;
    }
    
    public void setInDb(int inDb) {
        this.inDb = inDb;
    }
    public int getPresenting() {
        return this.presenting;
    }
    
    public void setPresenting(int presenting) {
        this.presenting = presenting;
    }




}


