package hibernate;
// Generated Jul 6, 2017 9:30:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Conference generated by hbm2java
 */
public class Conference  implements java.io.Serializable {


     private Integer id;
     private String name;
     private int place;
     private String field;
     private Date beginDate;
     private Date endDate;
     private Set<Myconferences> myconferenceses = new HashSet<Myconferences>(0);
     private Set<Agenda> agendas = new HashSet<Agenda>(0);
     private Set<Conferencemoderators> conferencemoderatorses = new HashSet<Conferencemoderators>(0);

    public Conference() {
    }

	
    public Conference(String name, int place, String field, Date beginDate) {
        this.name = name;
        this.place = place;
        this.field = field;
        this.beginDate = beginDate;
    }
    public Conference(String name, int place, String field, Date beginDate, Date endDate, Set<Myconferences> myconferenceses, Set<Agenda> agendas, Set<Conferencemoderators> conferencemoderatorses) {
       this.name = name;
       this.place = place;
       this.field = field;
       this.beginDate = beginDate;
       this.endDate = endDate;
       this.myconferenceses = myconferenceses;
       this.agendas = agendas;
       this.conferencemoderatorses = conferencemoderatorses;
    }
   
     public Conference(String name, int place, String field, Date beginDate, Date endDate) {
       this.name = name;
       this.place = place;
       this.field = field;
       this.beginDate = beginDate;
       this.endDate = endDate;
    }
    
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getPlace() {
        return this.place;
    }
    
    public void setPlace(int place) {
        this.place = place;
    }
    public String getField() {
        return this.field;
    }
    
    public void setField(String field) {
        this.field = field;
    }
    public Date getBeginDate() {
        return this.beginDate;
    }
    
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public Set<Myconferences> getMyconferenceses() {
        return this.myconferenceses;
    }
    
    public void setMyconferenceses(Set<Myconferences> myconferenceses) {
        this.myconferenceses = myconferenceses;
    }
    public Set<Agenda> getAgendas() {
        return this.agendas;
    }
    
    public void setAgendas(Set<Agenda> agendas) {
        this.agendas = agendas;
    }
    public Set<Conferencemoderators> getConferencemoderatorses() {
        return this.conferencemoderatorses;
    }
    
    public void setConferencemoderatorses(Set<Conferencemoderators> conferencemoderatorses) {
        this.conferencemoderatorses = conferencemoderatorses;
    }




}


