package hibernate;
// Generated Jul 6, 2017 9:30:01 PM by Hibernate Tools 4.3.1



/**
 * Favourites generated by hbm2java
 */
public class Favourites  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String favouriteUsername;

    public Favourites() {
    }

    public Favourites(String username, String favouriteUsername) {
       this.username = username;
       this.favouriteUsername = favouriteUsername;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getFavouriteUsername() {
        return this.favouriteUsername;
    }
    
    public void setFavouriteUsername(String favouriteUsername) {
        this.favouriteUsername = favouriteUsername;
    }




}


