package hibernate;
// Generated Jul 6, 2017 9:30:01 PM by Hibernate Tools 4.3.1

import org.omnifaces.cdi.GraphicImageBean;

/**
 * Gallery generated by hbm2java
 */
@GraphicImageBean
public class Gallery  implements java.io.Serializable {


     private Integer id;
     private Integer conferenceid;
     private Integer daynum;
     private Integer eventid;
     private String type;
     private byte[] image;

    public Gallery() {
    }

	
    public Gallery(String type, byte[] image) {
        this.type = type;
        this.image = image;
    }
    public Gallery(Integer conferenceid, Integer daynum, Integer eventid, String type, byte[] image) {
       this.conferenceid = conferenceid;
       this.daynum = daynum;
       this.eventid = eventid;
       this.type = type;
       this.image = image;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getConferenceid() {
        return this.conferenceid;
    }
    
    public void setConferenceid(Integer conferenceid) {
        this.conferenceid = conferenceid;
    }
    public Integer getDaynum() {
        return this.daynum;
    }
    
    public void setDaynum(Integer daynum) {
        this.daynum = daynum;
    }
    public Integer getEventid() {
        return this.eventid;
    }
    
    public void setEventid(Integer eventid) {
        this.eventid = eventid;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }




}


