package hibernate;
// Generated Jul 6, 2017 9:30:01 PM by Hibernate Tools 4.3.1



/**
 * Hall generated by hbm2java
 */
public class Hall  implements java.io.Serializable {


     private Integer id;
     private int location;
     private String conferenceHall;

    public Hall() {
    }

    public Hall(int location, String conferenceHall) {
       this.location = location;
       this.conferenceHall = conferenceHall;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getLocation() {
        return this.location;
    }
    
    public void setLocation(int location) {
        this.location = location;
    }
    public String getConferenceHall() {
        return this.conferenceHall;
    }
    
    public void setConferenceHall(String conferenceHall) {
        this.conferenceHall = conferenceHall;
    }




}


