package hibernate;
// Generated Jul 6, 2017 9:30:01 PM by Hibernate Tools 4.3.1



/**
 * Lecturegrade generated by hbm2java
 */
public class Lecturegrade  implements java.io.Serializable {


     private Integer id;
     private Lecture lecture;
     private int grade;
     private String username;

    public Lecturegrade() {
    }

    public Lecturegrade(Lecture lecture, int grade, String username) {
       this.lecture = lecture;
       this.grade = grade;
       this.username = username;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Lecture getLecture() {
        return this.lecture;
    }
    
    public void setLecture(Lecture lecture) {
        this.lecture = lecture;
    }
    public int getGrade() {
        return this.grade;
    }
    
    public void setGrade(int grade) {
        this.grade = grade;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }




}


