package hibernate;
// Generated Jul 6, 2017 9:30:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Lecture generated by hbm2java
 */
public class Lecture  implements java.io.Serializable {


     private Integer id;
     private Sessions sessions;
     private String name;
     private Date startTime;
     private Date endTime;
     private Set<Lecturegrade> lecturegrades = new HashSet<Lecturegrade>(0);
     private Set<Author> authors = new HashSet<Author>(0);
     private boolean rendered = false;
     
    public Lecture() {
    }

	
    public Lecture(Sessions sessions, String name, Date startTime, Date endTime) {
        this.sessions = sessions;
        this.name = name;
        this.startTime = startTime;
        this.endTime = endTime;
    }
    public Lecture(Sessions sessions, String name, Date startTime, Date endTime, Set<Lecturegrade> lecturegrades, Set<Author> authors) {
       this.sessions = sessions;
       this.name = name;
       this.startTime = startTime;
       this.endTime = endTime;
       this.lecturegrades = lecturegrades;
       this.authors = authors;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Sessions getSessions() {
        return this.sessions;
    }
    
    public void setSessions(Sessions sessions) {
        this.sessions = sessions;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
    public Set<Lecturegrade> getLecturegrades() {
        return this.lecturegrades;
    }
    
    public void setLecturegrades(Set<Lecturegrade> lecturegrades) {
        this.lecturegrades = lecturegrades;
    }
    public Set<Author> getAuthors() {
        return this.authors;
    }
    
    public void setAuthors(Set<Author> authors) {
        this.authors = authors;
    }

    public boolean isRendered() {
        return rendered;
    }

    public void setRendered(boolean rendered) {
        this.rendered = rendered;
    }

}


