package hibernate;
// Generated Jul 6, 2017 9:30:01 PM by Hibernate Tools 4.3.1



/**
 * Messages generated by hbm2java
 */
public class Messages  implements java.io.Serializable {


     private Integer id;
     private String userFrom;
     private String userFor;
     private String content;

    public Messages() {
    }

    public Messages(String userFrom, String userFor, String content) {
       this.userFrom = userFrom;
       this.userFor = userFor;
       this.content = content;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUserFrom() {
        return this.userFrom;
    }
    
    public void setUserFrom(String userFrom) {
        this.userFrom = userFrom;
    }
    public String getUserFor() {
        return this.userFor;
    }
    
    public void setUserFor(String userFor) {
        this.userFor = userFor;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }




}


