package hibernate;
// Generated Jul 6, 2017 9:30:01 PM by Hibernate Tools 4.3.1



/**
 * Myagenda generated by hbm2java
 */
public class Myagenda  implements java.io.Serializable {


     private Integer id;
     private Agenda agenda;
     private String username;
     private int idevent;
     private String type;
     private boolean likeOption;
     private String comment;

    public Myagenda() {
    }

    public Myagenda(Agenda agenda, String username, int idevent, String type, boolean likeOption, String comment) {
       this.agenda = agenda;
       this.username = username;
       this.idevent = idevent;
       this.type = type;
       this.likeOption = likeOption;
       this.comment = comment;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Agenda getAgenda() {
        return this.agenda;
    }
    
    public void setAgenda(Agenda agenda) {
        this.agenda = agenda;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public int getIdevent() {
        return this.idevent;
    }
    
    public void setIdevent(int idevent) {
        this.idevent = idevent;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public boolean isLikeOption() {
        return this.likeOption;
    }
    
    public void setLikeOption(boolean likeOption) {
        this.likeOption = likeOption;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }




}


