package hibernate;
// Generated Jul 6, 2017 9:30:01 PM by Hibernate Tools 4.3.1



/**
 * Myconferences generated by hbm2java
 */
public class Myconferences  implements java.io.Serializable {


     private Integer id;
     private Conference conference;
     private String username;

    public Myconferences() {
    }

    public Myconferences(Conference conference, String username) {
       this.conference = conference;
       this.username = username;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Conference getConference() {
        return this.conference;
    }
    
    public void setConference(Conference conference) {
        this.conference = conference;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }




}


