package hibernate;
// Generated Jul 6, 2017 9:30:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Sessions generated by hbm2java
 */
public class Sessions  implements java.io.Serializable {


     private Integer id;
     private Agenda agenda;
     private String name;
     private int hall;
     private Date date;
     private Date beginTime;
     private Date endTime;
     private int conferenceDay;
     private Set<Lecture> lectures = new HashSet<Lecture>(0);

    public Sessions() {
    }

	
    public Sessions(Agenda agenda, String name, int hall, Date date, Date beginTime, Date endTime, int conferenceDay) {
        this.agenda = agenda;
        this.name = name;
        this.hall = hall;
        this.date = date;
        this.beginTime = beginTime;
        this.endTime = endTime;
        this.conferenceDay = conferenceDay;
    }
    public Sessions(Agenda agenda, String name, int hall, Date date, Date beginTime, Date endTime, int conferenceDay, Set<Lecture> lectures) {
       this.agenda = agenda;
       this.name = name;
       this.hall = hall;
       this.date = date;
       this.beginTime = beginTime;
       this.endTime = endTime;
       this.conferenceDay = conferenceDay;
       this.lectures = lectures;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Agenda getAgenda() {
        return this.agenda;
    }
    
    public void setAgenda(Agenda agenda) {
        this.agenda = agenda;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getHall() {
        return this.hall;
    }
    
    public void setHall(int hall) {
        this.hall = hall;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Date getBeginTime() {
        return this.beginTime;
    }
    
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
    public int getConferenceDay() {
        return this.conferenceDay;
    }
    
    public void setConferenceDay(int conferenceDay) {
        this.conferenceDay = conferenceDay;
    }
    public Set<Lecture> getLectures() {
        return this.lectures;
    }
    
    public void setLectures(Set<Lecture> lectures) {
        this.lectures = lectures;
    }




}


