package hibernate;
// Generated Jul 6, 2017 9:30:01 PM by Hibernate Tools 4.3.1



/**
 * Sessionpause generated by hbm2java
 */
public class Sessionpause  implements java.io.Serializable {


     private Integer id;
     private Agenda agenda;
     private int length;

    public Sessionpause() {
    }

    public Sessionpause(Agenda agenda, int length) {
       this.agenda = agenda;
       this.length = length;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Agenda getAgenda() {
        return this.agenda;
    }
    
    public void setAgenda(Agenda agenda) {
        this.agenda = agenda;
    }
    public int getLength() {
        return this.length;
    }
    
    public void setLength(int length) {
        this.length = length;
    }




}


