package hibernate;
// Generated Jul 6, 2017 9:30:01 PM by Hibernate Tools 4.3.1

import org.omnifaces.cdi.GraphicImageBean;




/**
 * User generated by hbm2java
 */
@GraphicImageBean
public class User  implements java.io.Serializable {


     private String username;
     private String name;
     private String surname;
     private String password;
     private String email;
     private String gender;
     private byte[] profilePicture;
     private String shirtSize;
     private String linkedin;
     private String institution;
     private String type;

    public User() {
    }

	
    public User(String username) {
        this.username = username;
    }
    public User(String username, String name, String surname, String password, String email, String gender, byte[] profilePicture, String shirtSize, String linkedin, String institution, String type) {
       this.username = username;
       this.name = name;
       this.surname = surname;
       this.password = password;
       this.email = email;
       this.gender = gender;
       this.profilePicture = profilePicture;
       this.shirtSize = shirtSize;
       this.linkedin = linkedin;
       this.institution = institution;
       this.type = type;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public byte[] getProfilePicture() {
        return this.profilePicture;
    }
    
    public void setProfilePicture(byte[] profilePicture) {
        this.profilePicture = profilePicture;
    }
    public String getShirtSize() {
        return this.shirtSize;
    }
    
    public void setShirtSize(String shirtSize) {
        this.shirtSize = shirtSize;
    }
    public String getLinkedin() {
        return this.linkedin;
    }
    
    public void setLinkedin(String linkedin) {
        this.linkedin = linkedin;
    }
    public String getInstitution() {
        return this.institution;
    }
    
    public void setInstitution(String institution) {
        this.institution = institution;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


