package hibernate;
// Generated Jul 6, 2017 9:30:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Workshop generated by hbm2java
 */
public class Workshop  implements java.io.Serializable {


     private Integer id;
     private Agenda agenda;
     private String topic;
     private Date date;
     private Date beginTime;
     private Date endTime;
     private Set<Author> authors = new HashSet<Author>(0);
     private boolean rendered = false;
     private boolean imgrendered = false;
     
    public Workshop() {
    }

	
    public Workshop(Agenda agenda, String topic, Date date, Date beginTime, Date endTime) {
        this.agenda = agenda;
        this.topic = topic;
        this.date = date;
        this.beginTime = beginTime;
        this.endTime = endTime;
    }
    public Workshop(Agenda agenda, String topic, Date date, Date beginTime, Date endTime, Set<Author> authors) {
       this.agenda = agenda;
       this.topic = topic;
       this.date = date;
       this.beginTime = beginTime;
       this.endTime = endTime;
       this.authors = authors;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Agenda getAgenda() {
        return this.agenda;
    }
    
    public void setAgenda(Agenda agenda) {
        this.agenda = agenda;
    }
    public String getTopic() {
        return this.topic;
    }
    
    public void setTopic(String topic) {
        this.topic = topic;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Date getBeginTime() {
        return this.beginTime;
    }
    
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
    public Set<Author> getAuthors() {
        return this.authors;
    }
    
    public void setAuthors(Set<Author> authors) {
        this.authors = authors;
    }

    public boolean isRendered() {
        return rendered;
    }

    public void setRendered(boolean rendered) {
        this.rendered = rendered;
    }

    public boolean isImgrendered() {
        return imgrendered;
    }

    public void setImgrendered(boolean imgrendered) {
        this.imgrendered = imgrendered;
    }

}


